<?php

use SNOWGIRL_CORE\View;
use SNOWGIRL_SHOP\Catalog\URI;
use SNOWGIRL_SHOP\Entity\Tag;
use SNOWGIRL_CORE\Helper;

/** @var View $this */
/** @var Tag $tag */
?>

<?php $pk = Tag::getPk() ?>
<?php foreach ($this->tags as $tag) { ?>
    <a href="<?php echo (new URI($this->uriParams))
        ->set(URI::PAGE_NUM, null)
        ->inverse($pk, $tag->getId(), $isWas)
        ->output(URI::OUTPUT_DEFINED, false, $isNoFollow) ?>"
       class="nav-item<?php echo $isWas ? ' active' : '' ?>"
        <?php echo $isNoFollow ? 'rel="nofollow"' : '' ?>>
        <input type="checkbox"<?php echo $isWas ? ' checked' : '' ?>>
        <?php echo $tag->getName() ?>
        <?php if ($tmp = $tag->getRawVar('items_count')) { ?>
            <span class="count"><?php echo Helper::makeNiceNumber($tmp) ?></span>
        <?php } ?>
    </a>
<?php } ?>
