<?php

use SNOWGIRL_CORE\View;
use SNOWGIRL_SHOP\Catalog\URI;
use SNOWGIRL_SHOP\Entity\Tag;

/** @var View $this */
/** @var Tag $tag */
?>

<?php foreach ($this->types as $type) { ?>
    <a href="<?php echo (new URI($this->uriParams))->inverse($type, 1, $isWas)->output() ?>"
       class="btn btn-sm btn-block btn-default btn-<?php echo $type ?><?php echo $isWas ? ' active' : '' ?>">
        <?php echo $this->typesNames[$type] ?? $type ?>
    </a>
<?php } ?>