<?php
use SNOWGIRL_SHOP\View\Widget\Grid\Categories;
use SNOWGIRL_SHOP\Entity\Category;

/** @var Categories $this */
/** @var Category $category */
?>

<?php foreach ($this->items as $i => $category) { ?>
    <div class="col-xs-4 col-mb-<?php echo $this->tmpMap[$i] ?>">
        <a href="<?php echo $this->getLink($category) ?>" class="category<?php echo ($img = $category->getImage()) ? ' image' : '' ?>">
            <?php if ($img) { ?>
                <div class="category-cover" style="background-image:url(<?php echo $this->app->images->getLinkByFile($img) ?>)"></div>
            <?php } ?>
            <div class="category-caption">
                <span class="category-title h1"><?php echo $category->getBreadcrumb() ?: $category->getName() ?></span>
                <span class="category-info"><?php echo $this->getCount($category) ?> наименований</span>
            </div>
        </a>
    </div>
<?php } ?>
