<?php

use SNOWGIRL_CORE\View;
use SNOWGIRL_SHOP\Manager\Category as CategoryManager;

/** @var View $this */
$this->getLayout()
    ->setTitle($title = 'Дерево категорий')
    ->addBreadcrumb($title)
    ->setH1($title)
    ->addHeadCss('@shop/admin/categories.css')
    ->addJs('@core/jquery.nestable.js')
    ->addJs('@shop/admin/categories.js');
?>
<a class="btn btn-primary btn-toggle-collapse-all"><span class="glyphicon glyphicon-chevron-up"></span> Свернуть</a>
<a class="btn btn-success btn-build-tree"
   href="<?php echo $this->makeLink('admin', ['action' => 'categories-build-tree']) ?>"><span class="fa fa-tree"></span>
    Построить</a>

<?php echo $this->tree ?>