<?php

use SNOWGIRL_CORE\View;
use SNOWGIRL_SHOP\Entity\Import\Source as ImportSource;

/** @var View $this */
/** @var ImportSource $source */
$source = $this->source;

$this->getLayout()
    ->setTitle($title = 'Валидация источника ' . $source->getName())
    ->addBreadcrumb('Офферы', $this->makeLink('admin', 'offers'))
    ->addBreadcrumb($source->getName(), $this->makeLink('admin', ['action' => 'import-source', 'id' => $source->getId()]))
    ->addBreadcrumb('Валидация')
    ->setH1($title);
?>

<b>Columns:</b> <?php echo implode(', ', $this->columns) ?>
<?php if ($this->columns) { ?>
    <b class="text-success">OK</b>
<?php } else { ?>
    <b class="text-danger">FAILED</b>
<?php } ?>
<br><br>

<b>Filter columns:</b> <?php echo implode(', ', $this->filterColumns) ?>
<?php if ($this->filterColumnsDiff) { ?>
    <br>
    <b>Diff</b>: <?php echo implode(', ', $this->filterColumnsDiff) ?>
    <b class="text-danger">FAILED</b>
<?php } else { ?>
    <b class="text-success">OK</b>
<?php } ?>
<br><br>

<b>Mappping columns:</b> <?php echo implode(', ', $this->mappingColumns) ?>
<?php if ($this->mappingColumnsDiff) { ?>
    <br>
    <b>Diff</b>: <?php echo implode(', ', $this->mappingColumnsDiff) ?>
    <b class="text-danger">FAILED</b>
<?php } else { ?>
    <b class="text-success">OK</b>
<?php } ?>
<br><br>

<b>First filtered row:</b>
<?php if ($this->firstFilteredRow) { ?>
    <textarea style="width:100%;height:150px"><?php echo implode(';', $this->firstFilteredRow) ?></textarea>
    <b class="text-success">OK</b>
<?php } else { ?>
    <b class="text-warning">ABSENT</b>
<?php } ?>
<br><br>

<b>First passed row:</b>
<?php if ($this->firstPassedRow) { ?>
    <textarea style="width:100%;height:150px"><?php echo implode(';', $this->firstPassedRow) ?></textarea>
    <b class="text-success">OK</b>
<?php } else { ?>
    <b class="text-warning">ABSENT</b>
<?php } ?>
<br><br>

<b>First passed values:</b>
<?php if ($this->firstPassedValues) { ?>
    <textarea style="width:100%;height:150px"><?php echo implode(';', $this->firstPassedValues) ?></textarea>
    <b class="text-success">OK</b>
<?php } else { ?>
    <b class="text-warning">ABSENT</b>
<?php } ?>
<br><br>

