<?php
use SNOWGIRL_CORE\View;
use SNOWGIRL_CORE\Image;
use SNOWGIRL_SHOP\Entity\Item;

/** @var View $this */
/** @var Item $item */
?>

<div class="section items">
    <div class="container">
        <div class="section-title h2">Предложения</div>
        <?php echo $this->app->views->items([
            'items' => $this->items,
            'itemTemplate' => 'index',
            'class' => 'section-body'
        ], $this) ?>
    </div>
</div>