<?php

use SNOWGIRL_CORE\View;
use SNOWGIRL_CORE\Entity\Banner;
use SNOWGIRL_SHOP\Entity\Category;

/** @var View $this */
/** @var Banner $banner */
/** @var Category $category */

$categoriesBlocks = array_chunk($this->categories, $this->categoriesPerBlock);
$brandsBlocks = array_chunk($this->brands, $this->brandsPerBlock);
$itemsBlocks = array_chunk($this->items, $this->itemsPerBlock);

$this->getLayout()
    ->addHeadCss('@shop/index.css');

$vkontakteLike = $this->app->views->vkontakteLike($this)->stringify();
$facebookLike = $this->app->views->facebookLike($this)->stringify();
?>

<div class="index vs">
    <?php if ($this->mobileHeaderNav) { ?>
        <nav class="mobile-header-nav nav-sm" aria-label="Navigation" itemscope
             itemtype="http://schema.org/SiteNavigationElement">
            <?php foreach ($this->mobileHeaderNav as $text => $href) { ?>
                <a href="<?php echo $href ?>" class="nav-item" itemprop="url">
                    <span itemprop="name"><?php echo $text ?></span>
                </a>
            <?php } ?>
        </nav>
    <?php } ?>

    <?php if ($this->carousel) { ?>
        <div class="section top">
            <div class="container2">
                <?php echo $this->carousel ?>
            </div>
        </div>
    <?php } ?>

    <h1><?php echo $this->h1 ?></h1>

    <?php if ($this->mobileCatalogNav) { ?>
        <?php $this->getLayout()->addLazyCss('@app/index.catalog-nav.css'); ?>
        <nav class="mobile-catalog-nav nav-sm" aria-label="Navigation" itemscope
             itemtype="http://schema.org/SiteNavigationElement">
            <?php foreach ($this->mobileCatalogNav as $text => $href) { ?>
                <a href="<?php echo $href ?>" class="nav-item" itemprop="url">
                    <span class="icon"></span>
                    <span itemprop="name"><?php echo $text ?></span>
                </a>
            <?php } ?>
        </nav>
    <?php } ?>

    <?php if (isset($this->advantages)) { ?>
        <div class="section advantages">
            <div class="container">
                <div class="row">
                    <?php foreach ($this->advantages as $adv) { ?>
                        <div class="col-sm-4 advantage">
                            <div class="advantage-inner">
                                <span class="advantage-icon"
                                      style="background-image:url('<?php echo $adv[1] ?>')"></span>
                                <span class="advantage-text"><?php echo $adv[0] ?></span>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php } ?>

    <?php if ($vkontakteLike || $facebookLike) { ?>
        <div class="section subscribe">
            <?php echo $vkontakteLike ?>
            <?php echo $facebookLike ?>
        </div>
    <?php } ?>

    <?php $s = $this->repeatTimes;
    for ($i = 0; $i < $s; $i++) { ?>
        <?php
        $ii = $i + 1;
        ?>

        <?php if (isset($this->menu[$i])) { ?>
            <div class="container">
                <a href="<?php echo $this->app->managers->pages->getLink($this->menu[$i]) ?>"
                   class="link h1">
                    Популярное #<?php echo $ii ?>
                    <h2 class="link-external"><?php echo $this->menu[$i]->get('menu_title') ?></h2>
                </a>
            </div>
        <?php } ?>

        <?php echo isset($itemsBlocks[$i]) ? $this->app->views->get('@shop/index/items.phtml', [
            'items' => $itemsBlocks[$i],
            'currency' => $this->currency
        ], $this) : null ?>

        <?php echo isset($categoriesBlocks[$i]) ? $this->app->views->get('@shop/index/categories.phtml', [
            'grid' => $this->app->views->categories([
                'items' => $categoriesBlocks[$i],
                'right' => 1 == $i % 2
            ], $this)
        ], $this) : null ?>

        <?php echo isset($brandsBlocks[$i]) ? $this->app->views->get('@shop/index/brands.phtml', [
            'grid' => $this->app->views->brands([
                'items' => $brandsBlocks[$i],
                'padding' => 5
            ], $this)
        ], $this) : null ?>

        <?php if (0 == $i) { ?>
            <?php echo $this->banner ?>
        <?php } ?>
    <?php } ?>
</div>